# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFf4TUd4LanpPhKhQXAhrnv5r91ULUNV
"""

from typing import Iterator, Iterable, Optional, Tuple, Sequence, List, Dict
import numpy as np
from dataclasses import dataclass
### bitstring utilities ###
def _gosper_next(x: int) -> int:
    """
    Return next higher integer with same number of 1-bits.
    If overflow (no next within the same bit-length), result will exceed limit.
    """
    c = x & -x
    r = x + c
    return (((r ^ x) >> 2) // c) | r

def _all_dets_bitwise(n_orb: int, n_e: int):
    """
    Yield all determinants (bitstrings) with exactly n_e electrons
    in n_orb orbitals, as Python ints.
    """
    if n_e < 0 or n_e > n_orb:
        return
    if n_e == 0:
        yield 0
        return

    x = (1 << n_e) - 1              # e.g. 000111
    limit = 1 << n_orb              # stop when we exceed n_orb bits

    while x < limit:
        yield x
        x = _gosper_next(x)

def _interleave_up_bits(x: int) -> int:
    """
    Map compact up bitstring x (bit i = site i) to global determinant bits (2*i).
    """
    det = 0
    while x:
        lsb = x & -x
        i = lsb.bit_length() - 1
        det |= 1 << (2*i)
        x ^= lsb
    return det

def _interleave_dn_bits(y: int) -> int:
    """
    Map compact down bitstring y (bit j = site j) to global determinant bits (2*j+1).
    """
    det = 0
    while y:
        lsb = y & -y
        j = lsb.bit_length() - 1
        det |= 1 << (2*j + 1)
        y ^= lsb
    return det

def _configs_interleaved_spin_fast(
    n_up_sites: int,
    n_dn_sites: int,
    n_up_e: int,
    n_dn_e: int
):
    if n_up_e < 0 or n_up_e > n_up_sites:
        return
    if n_dn_e < 0 or n_dn_e > n_dn_sites:
        return

    # compact bitstrings (length n_up_sites / n_dn_sites)
    if n_up_e == 0:
        up_list = [0]
    else:
        x = (1 << n_up_e) - 1
        limit = 1 << n_up_sites
        up_list = []
        while x < limit:
            up_list.append(x)
            x = _gosper_next(x)

    if n_dn_e == 0:
        dn_list = [0]
    else:
        y = (1 << n_dn_e) - 1
        limit = 1 << n_dn_sites
        dn_list = []
        while y < limit:
            dn_list.append(y)
            y = _gosper_next(y)

    for x in up_list:
        det_up = _interleave_up_bits(x)
        for y in dn_list:
            det_dn = _interleave_dn_bits(y)
            yield det_up | det_dn

def _apply_creation(det: int, p: int) -> Tuple[Optional[int], int]:
    """
    Apply fermionic creation operator c_p^† to |det>.
    Returns (new_det, sign). If result is zero, returns (None, 0).
    """
    # already occupied -> zero
    if (det >> p) & 1:
        return None, 0

    # number of occupied orbitals with index < p
    left_mask = (1 << p) - 1
    n_left = (det & left_mask).bit_count()
    sign = -1 if (n_left & 1) else +1

    new_det = det | (1 << p)
    return new_det, sign

def _apply_annihilation(det: int, p: int) -> Tuple[Optional[int], int]:
    """
    Apply fermionic annihilation operator c_p to |det>.
    Returns (new_det, sign). If result is zero, returns (None, 0).
    """
    # unoccupied -> zero
    if ((det >> p) & 1) == 0:
        return None, 0

    left_mask = (1 << p) - 1
    n_left = (det & left_mask).bit_count()
    sign = -1 if (n_left & 1) else +1

    new_det = det & ~(1 << p)
    return new_det, sign

def _count_up_dn(det: int, n_sites: int) -> Tuple[int, int, int]:
    """
    Count electrons in an interleaved bitstring det with 2*n_sites bits:
      up  at bit 2*i
      down at bit 2*i+1

    Returns (N_total, N_up, N_dn).
    """
    # Mask selecting all even bits in the first 2*n_sites positions: 010101...
    even_mask = 0
    for i in range(n_sites):
        even_mask |= 1 << (2*i)

    up = (det & even_mask).bit_count()
    total = (det & ((1 << (2*n_sites)) - 1)).bit_count()
    dn = total - up
    return total, up, dn

def masks_from_ctr_ls(ctr_ls: Sequence[Sequence[int]]) -> List[int]:
    """Precompute bitmasks for each rs in ctr_ls."""
    masks = []
    for rs in ctr_ls:
        m = 0
        for r in rs:
            m |= (1 << r)
        masks.append(m)
    return masks

def _compute_occ_bits_from_masks(det: int, masks: Sequence[int]) -> Sequence[int]:
    """
    Returns a NumPy array of 0/1 for each mask:
      out[i] = 1 iff (det & masks[i]) == masks[i]
    """
    #out = np.empty(len(masks), dtype=np.int8)
    out = [None] * len(masks)
    for i, m in enumerate(masks):
        out[i] = 1 if (det & m) == m else 0
    return tuple(out)
def _occupied_indices(det: int) -> List[int]:
    """Return list of occupied bit indices (ascending)."""
    occ = []
    x = det
    while x:
        lsb = x & -x                 # isolates lowest 1-bit
        p = lsb.bit_length() - 1     # index of that bit
        occ.append(p)
        x &= x-1                     # clear that bit
    return occ
def _virtual_indices(det: int, n_orb: int) -> List[int]:
    mask = (1 << n_orb) - 1
    vir_bits = (~det) & mask
    return _occupied_indices(vir_bits)

def _single_dets(det: int, n_orb: int):
    occs = _occupied_indices(det)
    virs = _virtual_indices(det, n_orb)
    for i in occs:
        bi = 1 << i
        for a in virs:
            yield det ^ bi ^ (1 << a)

def _double_dets(det: int, n_orb: int):
    occs = _occupied_indices(det)
    virs = _virtual_indices(det, n_orb)
    occ_bits = [1 << i for i in occs]
    vir_bits = [1 << a for a in virs]
    for ii in range(len(occs)):
        bi = occ_bits[ii]
        for jj in range(ii + 1, len(occs)):
            bij = bi ^ occ_bits[jj]
            for aa in range(len(virs)):
                ba = vir_bits[aa]
                for bb in range(aa + 1, len(virs)):
                    yield det ^ bij ^ ba ^ vir_bits[bb]

def _iter_set_bits(x: int) -> Iterator[int]:
    while x:
        lsb = x & -x
        yield lsb.bit_length() - 1
        x &= x - 1

@dataclass(frozen=True)
class SpinInterleavedPrecomp:
    n_orb: int                 # total interleaved orbitals (bits 0..n_orb-1)
    n_up: int                  # number of even orbitals
    n_dn: int                  # number of odd orbitals
    mask_all: int
    mask_even: int
    mask_odd: int
    up_full: int               # (1<<n_up)-1
    dn_full: int               # (1<<n_dn)-1
    even_bit: Tuple[int, ...]  # even_bit[k] = 1<<(2k)
    odd_bit: Tuple[int, ...]   # odd_bit[k]  = 1<<(2k+1)

def precompute_for_exc_ls(n_orb: int) -> SpinInterleavedPrecomp:
    # count evens/odds within 0..n_orb-1
    n_up = (n_orb + 1) // 2
    n_dn = n_orb // 2

    mask_all = (1 << n_orb) - 1

    # even mask via 0x55.. pattern, then clip to n_orb bits
    base_even = int('5' * ((n_orb + 3) // 4), 16)
    mask_even = base_even & mask_all
    mask_odd = mask_all ^ mask_even

    even_bit = tuple(1 << (2 * k) for k in range(n_up))
    odd_bit  = tuple(1 << (2 * k + 1) for k in range(n_dn))

    return SpinInterleavedPrecomp(
        n_orb=n_orb,
        n_up=n_up,
        n_dn=n_dn,
        mask_all=mask_all,
        mask_even=mask_even,
        mask_odd=mask_odd,
        up_full=(1 << n_up) - 1,
        dn_full=(1 << n_dn) - 1,
        even_bit=even_bit,
        odd_bit=odd_bit
    )

def _compact_lists_from_interleaved(det: int, pc: SpinInterleavedPrecomp):
    """
    From interleaved det -> lists of compact occupied/virtual indices for up and down.
    Compact index k corresponds to interleaved:
      up: p = 2k
      dn: p = 2k+1
    Returns: (occ_up, vir_up, occ_dn, vir_dn)
    """
    d = det & pc.mask_all

    # occupied even/odd positions in interleaved indexing
    occ_even_pos = d & pc.mask_even
    occ_odd_pos  = d & pc.mask_odd

    # build compact occupation bitstrings by iterating occupied positions
    occ_up_comp = 0
    for p in _iter_set_bits(occ_even_pos):
        occ_up_comp |= 1 << (p >> 1)

    occ_dn_comp = 0
    for p in _iter_set_bits(occ_odd_pos):
        occ_dn_comp |= 1 << (p >> 1)

    # compact virtual bitstrings
    vir_up_comp = (~occ_up_comp) & pc.up_full
    vir_dn_comp = (~occ_dn_comp) & pc.dn_full

    # lists (compact indices)
    occ_up = list(_iter_set_bits(occ_up_comp))
    vir_up = list(_iter_set_bits(vir_up_comp))
    occ_dn = list(_iter_set_bits(occ_dn_comp))
    vir_dn = list(_iter_set_bits(vir_dn_comp))

    return occ_up, vir_up, occ_dn, vir_dn

def _singles_spin_conserving_fast(det: int, pc: SpinInterleavedPrecomp) -> List[int]:
    """
    All spin-conserving singles from interleaved det, returned as interleaved dets.
    up: even->even ; dn: odd->odd
    """
    d = det & pc.mask_all
    occ_up, vir_up, occ_dn, vir_dn = _compact_lists_from_interleaved(d, pc)

    out: List[int] = []
    out_append = out.append

    # up singles
    even_bit = pc.even_bit
    for i in occ_up:
        bi = even_bit[i]
        for a in vir_up:
            out_append(d ^ bi ^ even_bit[a])

    # down singles
    odd_bit = pc.odd_bit
    for i in occ_dn:
        bi = odd_bit[i]
        for a in vir_dn:
            out_append(d ^ bi ^ odd_bit[a])

    return out

def _doubles_spin_conserving_fast(det: int, pc: SpinInterleavedPrecomp) -> List[int]:
    d = det & pc.mask_all
    occ_up, vir_up, occ_dn, vir_dn = _compact_lists_from_interleaved(d, pc)

    out: List[int] = []
    out_append = out.append

    even_bit = pc.even_bit
    odd_bit  = pc.odd_bit

    # (1) up-up -> up-up
    for ii in range(len(occ_up)):
        bi = even_bit[occ_up[ii]]
        for jj in range(ii + 1, len(occ_up)):
            bij = bi ^ even_bit[occ_up[jj]]
            for aa in range(len(vir_up)):
                ba = even_bit[vir_up[aa]]
                for bb in range(aa + 1, len(vir_up)):
                    out_append(d ^ bij ^ ba ^ even_bit[vir_up[bb]])

    # (2) dn-dn -> dn-dn
    for ii in range(len(occ_dn)):
        bi = odd_bit[occ_dn[ii]]
        for jj in range(ii + 1, len(occ_dn)):
            bij = bi ^ odd_bit[occ_dn[jj]]
            for aa in range(len(vir_dn)):
                ba = odd_bit[vir_dn[aa]]
                for bb in range(aa + 1, len(vir_dn)):
                    out_append(d ^ bij ^ ba ^ odd_bit[vir_dn[bb]])

    # (3) up-dn -> up-dn
    for i in occ_up:
        bi = even_bit[i]
        for j in occ_dn:
            bij = bi ^ odd_bit[j]
            for a in vir_up:
                ba = even_bit[a]
                for b in vir_dn:
                    out_append(d ^ bij ^ ba ^ odd_bit[b])

    return out

def _bitstring_from_occupied(n_orb: int, occ_orbs: Iterable[int]) -> int:
    """
    Build bitstring det for orbitals 0..n_orb-1 given occupied orbital indices.
    """
    det = 0
    for p in occ_orbs:
        if p < 0 or p >= n_orb:
            raise ValueError(f"orbital index {p} out of range [0,{n_orb-1}]")
        det |= 1 << p
    return det

def _excite_single(x: int, i: int, a: int):
    if ((x >> i) & 1) == 0 or ((x >> a) & 1) == 1:
        return None

    if i < a:
        mask = ((1 << a) - 1) ^ ((1 << (i + 1)) - 1)
    else:
        mask = ((1 << i) - 1) ^ ((1 << (a + 1)) - 1)

    sign = -1 if ((x & mask).bit_count() & 1) else 1
    y = x ^ (1 << i) ^ (1 << a)
    return y, sign

def _excite_double(x: int, i: int, j: int, a: int, b: int):
    if (i == j) or (a == b) or (i == a) or (i == b) or (j == a) or (j == b):
        return None

    if (((x >> i) & 1) == 0 or
        ((x >> j) & 1) == 0 or
        ((x >> a) & 1) == 1 or
        ((x >> b) & 1) == 1):
        return None

    sign = 1
    m = x

    if (m & ((1 << j) - 1)).bit_count() & 1:
        sign = -sign
    m ^= (1 << j)

    if (m & ((1 << i) - 1)).bit_count() & 1:
        sign = -sign
    m ^= (1 << i)

    if (m & ((1 << b) - 1)).bit_count() & 1:
        sign = -sign
    m |= (1 << b)

    if (m & ((1 << a) - 1)).bit_count() & 1:
        sign = -sign
    m |= (1 << a)

    return m, sign

### VMC fxns, force numpy ints into int type ###
def get_exc_list_u1(x,nsite,nexs=2):
    if nexs>2:
        raise ValueError
    nsite = int(nsite)
    ls = []
    if nexs>=1:
        ls += list(_single_dets(x,nsite))
    if nexs>=2:
        ls += list(_double_dets(x,nsite))
    return ls

def get_exc_list_u11(x,pc,nexs=2):
    if nexs>2:
        raise ValueError
    ls = []
    if nexs>=1:
        ls += _singles_spin_conserving_fast(x,pc)
    if nexs>=2:
        ls += _doubles_spin_conserving_fast(x,pc)
    return ls

def get_config_from_occ(occ,nsite):
    occ = [int(p) for p in occ]
    return _bitstring_from_occupied(int(nsite),occ)

def get_all_configs_u1(nsites,nelecs):
    return list(_all_dets_bitwise(int(nsites),int(nelecs)))

def get_all_configs_u11(nsites,nelecs):
    return list(_configs_interleaved_spin_fast(int(nsites[0]),int(nsites[1]),int(nelecs[0]),int(nelecs[1])))

def fermion_act(x,oix,typ):
    if typ=='cre':
        return _apply_creation(x,int(oix))
    elif typ=='des':
        return _apply_annihilation(x,int(oix))
    else:
        raise ValueError

def string_act(x,ops,order=-1):
    if order==-1:
        ops = ops[::-1]
    s = 1
    y = x
    for i,(oix,typ) in enumerate(ops):
        y,si = fermion_act(y,int(oix),typ)
        if y is None:
            return None,0
        s *= si
    return y,s

def check_symmetry(x,symmetry,nsite,nelec):
    N,Na,Nb = _count_up_dn(x,int(nsite//2))
    if symmetry=='u1':
        if N!=sum(nelec):
             return False
    if symmetry=='u11':
        if Na!=nelec[0]:
            return False
        if Nb!=nelec[1]:
            return False
    return True
def ctr_ls_to_masks(ctr_ls):
    if ctr_ls is None:
        return None
    return masks_from_ctr_ls(ctr_ls)
def ctr_ls_to_occ(cf,masks):
    return _compute_occ_bits_from_masks(cf,masks)
def get_occ_indices(cf):
    return _occupied_indices(cf)
def get_vir_indices(cf,nsite):
    return _virtual_indices(cf,int(nsite))
def excite_single(x,i,a):
    return _excite_single(x,int(i),int(a))
def excite_double(x,i,j,a,b):
    return _excite_double(x,int(i),int(j),int(a),int(b))
def count_double_occupancy(det: int, n_sites: int) -> int:
    """
    O(#electrons) method: iterate occupied bits and accumulate compact up/dn site masks,
    then popcount their AND.
    """
    det = int(det)
    d = det & ((1 << (2 * n_sites)) - 1)

    up_comp = 0
    dn_comp = 0
    for p in _iter_set_bits(d):
        site = p >> 1          # floor(p/2)
        if (p & 1) == 0:       # even -> up
            up_comp |= 1 << site
        else:                  # odd -> down
            dn_comp |= 1 << site

    return (up_comp & dn_comp).bit_count()
def all_bitstrings_list(n_sites: int) -> list[int]:
    n_orb = 2 * n_sites
    return list(range(1 << n_orb))

def apply_c_dag_to_state(
    psi: np.ndarray,
    dets: Sequence[int],
    q: int,
    det_to_index: Optional[Dict[int, int]] = None,
) -> np.ndarray:
    """
    Compute phi = c_q^† |psi> in the same basis 'dets'.

    Convention:
      - det is a Python int bitstring; bit p=1 means occupied.
      - fermionic sign for c_q^† is (-1)^(N_{<q}) where N_{<q} is the number
        of occupied orbitals with index < q in the current determinant.

    If the basis 'dets' does not contain the resulting determinant (common if
    your basis is fixed-N), that contribution is skipped (i.e. projected out).

    Args:
      psi: shape (dim,) complex/float
      dets: length dim list/array of bitstrings
      q: orbital index to create on
      det_to_index: optional dict mapping det->index; if None, it is built.

    Returns:
      phi: shape (dim,) same dtype as psi
    """
    psi = np.asarray(psi)
    dim = len(dets)
    if psi.shape[0] != dim:
        raise ValueError("psi and dets must have the same length")

    q = int(q)
    bitq = 1 << q
    left_mask = bitq - 1  # bits < q

    if det_to_index is None:
        det_to_index = {int(d): i for i, d in enumerate(dets)}

    phi = np.zeros_like(psi)

    for i, d in enumerate(dets):
        d = int(d)

        # if already occupied at q, creation gives zero
        if d & bitq:
            continue

        d_new = d | bitq

        j = det_to_index.get(d_new)
        if j is None:
            # result not in this basis (e.g., fixed-N basis) -> projected out
            continue

        # fermionic phase = (-1)^(popcount of occupied bits below q)
        n_left = (d & left_mask).bit_count()
        sgn = -1 if (n_left & 1) else +1

        phi[j] += sgn * psi[i]

    return phi
def apply_c_to_state(
    psi: np.ndarray,
    dets: Sequence[int],
    p: int,
    det_to_index: Optional[Dict[int, int]] = None,
) -> np.ndarray:
    """
    Compute phi = c_p |psi> in the same basis 'dets'.

    Convention:
      - det is a Python int bitstring; bit q=1 means occupied.
      - fermionic sign for c_p is (-1)^(N_{<p}) where N_{<p} counts occupied
        orbitals with index < p in the CURRENT determinant.

    If the resulting determinant is not in 'dets', the contribution is skipped.

    Args:
      psi: shape (dim,) complex/float
      dets: length dim list/array of determinants (Python ints recommended)
      p: orbital index
      det_to_index: optional dict mapping det->index; if None, built internally

    Returns:
      phi: shape (dim,) same dtype as psi
    """
    psi = np.asarray(psi)
    dim = len(dets)
    if psi.shape[0] != dim:
        raise ValueError("psi and dets must have the same length")

    p = int(p)
    bitp = 1 << p
    left_mask = bitp - 1

    if det_to_index is None:
        det_to_index = {int(d): i for i, d in enumerate(dets)}

    phi = np.zeros_like(psi)
    get = det_to_index.get  # local binding for speed

    for i, d in enumerate(dets):
        d = int(d)
        amp = psi[i]
        if amp == 0:
            continue

        # if p unoccupied -> annihilation gives zero
        if (d & bitp) == 0:
            continue

        d_new = d & ~bitp
        j = get(d_new)
        if j is None:
            continue

        n_left = (d & left_mask).bit_count()
        if n_left & 1:
            phi[j] -= amp
        else:
            phi[j] += amp

    return phi
def _iter_set_bits_new(x: int):
    while x:
        lsb = x & -x
        yield lsb
        x &= x - 1
def apply_a_dag_dense_sign(
    psi: np.ndarray,
    dets: Sequence[int],
    A_col: np.ndarray,                 # shape (n_orb,)
    n_orb: int,
    det_to_index: Optional[Dict[int, int]] = None,
) -> np.ndarray:
    """
    Same as above but includes fermionic sign for c_q^†.
    """
    psi = np.asarray(psi)
    A = np.asarray(A_col)
    dim = len(dets)
    if psi.shape[0] != dim:
        raise ValueError("psi and dets must have the same length")
    if A.shape[0] != n_orb:
        raise ValueError("A_col must have length n_orb")

    if det_to_index is None:
        det_to_index = {int(d): k for k, d in enumerate(dets)}

    mask_all = (1 << int(n_orb)) - 1
    phi = np.zeros_like(psi)

    get = det_to_index.get
    A_list = A.tolist()

    for k, d in enumerate(dets):
        amp = psi[k]
        if amp == 0:
            continue
        d = int(d) & mask_all

        vir = (~d) & mask_all
        for bq in _iter_set_bits_new(vir):
            q = bq.bit_length() - 1
            Aq = A_list[q]
            if Aq == 0:
                continue

            d_new = d | bq
            j = get(d_new)
            if j is None:
                continue

            # sign = (-1)^(popcount of occupied bits below q)
            n_left_odd = ((d & (bq - 1)).bit_count() & 1)
            if n_left_odd:
                phi[j] -= Aq * amp
            else:
                phi[j] += Aq * amp

    return phi
